name: Install and Build

on: workflow_call

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      PIP_INDEX_URL: https://artifactory.eng.nimblestorage.com/artifactory/api/pypi/pypi/simple
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          echo Installing dependencies...
          pip install --index-url ${{ env.PIP_INDEX_URL }}  --no-cache-dir --upgrade pip
          pip install --index-url ${{ env.PIP_INDEX_URL }}  --no-cache-dir --requirement requirements-test.txt
          pip install --index-url ${{ env.PIP_INDEX_URL }} --no-cache-dir --upgrade nimblezeus
      - name: Linter 
        run: |
          echo Running Linter Steps...
          # Possibly Add ${{ github.sha }} to fix logic and compare w/ ${{ env.BASE_SHA }}
          git diff --name-only --diff-filter=ACMRTUX ${{ env.BASE_SHA }} | grep -E .pyi*$  | xargs --max-lines=50000 --no-run-if-empty flake8
          git diff --name-only --diff-filter=ACMRTUX ${{ env.BASE_SHA }}| grep -E .pyi*$ | xargs --max-lines=50000 --no-run-if-empty black --target-version py38 --check
      - name: Package 
        run: |
          git checkout pull/${{ github.event.pull_request.number }}/merge &&
          pip install --no-cache-dir -e . &&
          echo "insert appropriate pytest command line for unit testing ( no hardware requirements )" &&
          python setup.py bdist_wheel bdist_egg egg_info --tag-build .b${{ github.event.pull_request.number }}.post${IRONFORGE_COMMIT_COUNT} &&
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          # Before Edit : python -m twine upload -r artifactory --disable-progress-bar dist/*
          # Removed -r artifactory to use TWINE env vars instead
          run: python -m twine upload --disable-progress-bar dist/*
