name: CI

on:
  # Triggers the workflow on push or pull request events to 'prod'
  push:
    branches: 
      - '*'
  pull_request_target:
    types:
      - opened
    branches: [ "prod" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is called "build"
  build:
    # Github creates a ubuntu image to checkout repo, compile, package.
    runs-on: ubuntu-latest

    # Tasks that will be executed as part of the job "build"
    steps:
      - uses: actions/checkout@v3

      - name: Echo GitHub Actions Secret
        run: |
          echo PASSWORD token is: 
          echo ${{secrets.PASSWORD}}

      - name: Check Python Version
        run: |
          echo What is the python version,
          python --version
      - name: Check pip Version
        run: |
          echo What is the python version,
          pip --version
