name: CI

on:
  # Triggers the workflow on push or pull request events to 'prod'
  push:
    branches: 
      - '*'
  pull_request_target:
    types:
      - opened
    branches: [ "prod" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is called "build"
  build:
    # Github creates a ubuntu image to checkout repo, compile, package.
    runs-on: ubuntu-latest

    # Tasks that will be executed as part of the job "build"
    steps:
      - uses: actions/checkout@v3

      - name: Echo GitHub Actions Secret
        run: |
          echo PASSWORD token is: 
          echo ${{secrets.PASSWORD}}

      - name: Check Python Version
        run: |
          echo What is the python version,
          python --version
          python -m pip install --upgrade pip
      - name: Check pip Version
        run: |
          echo What is the python version,
          pip --version
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
          prNumber: ${{ github.event.pull_request.number }}
          output: ' '
      - name: Run lint
        uses: samuelmeuli/lint-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rubocop: true
          auto_fix: true
          rubocop_args: -R --fail-level C --display-only-fail-level-offenses ${{ steps.get_file_changes.outputs.files}}
          rubocop_command_prefix: bundle exec
