

name: Push to main

on:
  pull_request:
    types: [labeled]
  
  workflow_dispatch:

jobs:
  merge:
    if: ${{ github.event.label.name == 'merge2master' }}
    runs-on: ubuntu-latest
    env:
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Rebase
        shell: bash
        run: |
          git config --global user.email "cfl@hpe.com"
          git config --global user.name "CFL"
          git fetch
          git checkout test3 
          git rebase -p origin/main test3 
          git push -f origin/test3
