

name: Push to main

on:
  pull_request:
    types: [labeled]
  
  workflow_dispatch:

jobs:
  merge:
    if: ${{ github.event.label.name == 'merge2master' }}
    runs-on: ubuntu-latest
    env:
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Rebase
        shell: bash
        run: |
          git config --global user.email "cfl@hpe.com"
          git config --global user.name "CFL"
          echo "Triggered by commit $(git log -1 --format='%H')"
          git pull --no-commit
          git reset --hard origin/main
          echo "Jumped to commit $(git log -1 --format='%H')"
          git rebase origin/test3 main
          git push
